// (C) Copyright 2014-2018 The Khronos Group Inc. All Rights Reserved.
// Khrono Group Safety Critical API Development SCAP
// document
//
// Text format: asciidoc 8.6.9
// Editor:      Asciidoc Book Editor
//
// Description: Requirements acknowledgements

:Author: Illya Rudkin (spec editor)
:Author Initials: IOR
:Revision: 0.053

=== Acknowledgements

Safety Critical API Development guidelines and
requirements is the result of the contributions by many people, representing a cross section of the safety critical software development community in a range of industries. Following is a list of the contributors, including the company that they represented at the time of their contribution:

*Working group chair:* +
- Illya Rudkin, Codeplay Ltd +

*External expert contributions:* +
- Andreas Urbán, SAAB Aerospace +

*Khronos contributors:* +
- Erik Noreke, independent +
- Ajay Jayaraj, Texas Instruments +
- Bob Shulman, AMD +
- Daniel Herring, Core Avionics +
- Mika Leppinen, Nvidia +
- Mathias Heyer, Nvidia +
- Radha Giduthuri, AMD +
- Julien Olivain, NXP +
- Gregory Sikkens, Core Avionics +
- Bogdan Naodovic, Nvidia +
- Mandar Pitale, Nvidia +

NOTE: Up-to-date PDF version of this document may be found on the Khronos(R) web site under Documents->Khronos SC Advisory Forum->Accessible to Advisors. You must be logged into the Khronos web site.

NOTE: You can also visit the Khronos Safety Critical Advisory Forum web page here for more information at https://www.khronos.org/advisors/kscaf
