// (C) Copyright 2014-2018 The Khronos Group Inc. All Rights Reserved.
// Khrono Group Safety Critical API Development SCAP requirements document
// Text format: asciidoc 8.6.9
// Editor: Asciidoc Book Editor

:Author: Daniel Herring
:Author Initials: DMH
:Revision: 0.052

// Hyperlink anchor, the ID matches those in
// 3_1_RequirementList.adoc
[[gh2_3_10]]

ifdef::basebackend-docbook[]
=== Safety Critical Software Development Guideline and Standards
endif::[]
ifdef::basebackend-html[]
=== {chapter-id}.{counter:chapter-sub-id}. Safety Critical Software Development Guideline and Standards
endif::[]

Expertise with the following guidelines and standards have been considered during the development of this document. The KSCAF is aware of the existence of other safety related standards and guidelines and welcomes experts in the use of other standards to contribute to this document. Please contact the KSCAF working group using the contact information provided on the Khronos web site's KSCAF About page to request membership to the panel.

Each requirement in this document tries to list the relevancy to the listed development guidelines and standards.

==== DO-178C/ED-12C
*Software Considerations in Airborne Systems and Equipment Certification* is the safety
critical software development standard used for development avionics software. This
standard defines 5 levels of safety criticality referred to as Design Assurance
Level(DAL), they are numerated A, B, C, D, E. The most strict safety critical software is
referred to as DAL A, and caries the largest amount of development process requirements.
DAL E software is considered non safety critical. This document strives to allow API
specifications to be compatible with the required DO-178/ED-12C objectives for DAL A
systems.

==== ISO 26262
*Road vehicles – Functional safety* is an international standard which strives to define
the needed processes and requirements for development of safety critical electronics for
automotive vehicles.This standard uses 5 levels of safety criticality referred to as
Automotive Safety Integrity Levels (ASIL). The most strict safety critical software is
referred to as ASIL D, with the least strict being ASIL A, with a 5th as Quality
Management (QM) which is similar to DO-178 DAL E. This document strives to allow API
specifications to be compatible with ISO 26262 ASIL D.

==== IEC 62304
*Medical device software – software life cycle processes* is another international
standard with similar objectives of the others, but in this case for medical devices.
Similar to the other standards this standard splits the criticality of software in to categories referred to as Classes. Class 3 having the highest criticality and Class 1 having the lowest. This document strives to allow API specifications to be compatible with IEC 62304 Class 3 software development requirements.
