// (C) Copyright 2014-2018 The Khronos Group Inc. All Rights Reserved.
// Khrono Group Safety Critical API Development SCAP
// document
//
// Text format: asciidoc 8.6.9
// Editor:      Asciidoc Book Editor
//
// Description: Requirements 1.0 Introduction

:Author: Illya Rudkin (spec editor)
:Author Initials: IOR
:Revision: 0.053

// Automatic chapter sub numbering, use {counter:chapter-sub-id}
:chapter-sub-id: 0

// This text is a near duplication of the text in the KSCAF Guidelines Introduction chapter
ifdef::basebackend-docbook[]
== Introduction
endif::[]
ifdef::basebackend-html[]
== {counter:chapter-id}. Introduction
endif::[]

ifdef::basebackend-docbook[]
=== Khronos(R) Safety Critical Advisory Forum
endif::[]
ifdef::basebackend-html[]
=== {chapter-id}.{counter:chapter-sub-id}. Khronos(R) Safety Critical Advisory Forum
endif::[]

The Khronos(R) Safety Critical Advisory Forum (KSCAF) is a workgroup to create requirements and guidelines for the design of new Khronos safety critical graphics, compute and vision processing APIs or the refactoring of their existing APIs to a safety critical (SC) version.

KSCAF is an IP free workgroup whose purpose is to formulate SC design requirements and guidelines and not the detailed API design for ratification. The design is undertaken by the appropriate working group itself or a technical sub-group of the working group.

This document is intended for the following types of developers:

•	Developers with no previous experience of developing SC software
•	Developers designing an API for a non-SC purpose but would like to consider SC recommendations or guidelines in the design
•	Developers with existing SC development experience participating in a Khronos Working Group

KSCAF is open to both Khronos members and invited experts from the various SC industries. The Requirements and Guideline documents are open source so they may be continually improved, capture and evolve with the many considerations and practices required by existing SC domains. The goals of KSCAF are to:

•	Widen the acceptable use of Khronos APIs for as many SC domains as possible
•	Reduce potential API design faults or omissions that make meeting SC requirements difficult or impossible
•	Make it easier to implement development testing
•	Enabling an implementation to better meet and pass a SC specification

We assume the reader has experience in software development in general and has at a least some rudimentary understanding of programming best practices and the implications and consequences of writing software if not written with rigor and oversight.

ifdef::basebackend-docbook[]
=== The Requirements
endif::[]
ifdef::basebackend-html[]
=== {chapter-id}.{counter:chapter-sub-id}. The Requirements
endif::[]

This document, referred to as the KSCAF Requirements document which states requirements that must be strongly and implemented when designing a Khronos API which it to be used for SC software development. A reason would normally need to be recorded as to why a particular requirement was not implemented.

ifdef::basebackend-docbook[]
=== The Guidelines
endif::[]
ifdef::basebackend-html[]
=== {chapter-id}.{counter:chapter-sub-id}. The Guidelines
endif::[]

There is an accompanying KSCAF Guidelines document with development guide lines for developing the same SC API. The Guidelines document is meant to be used together with this Requirements document.
