// (C) Copyright 2014-2017 The Khronos Group Inc. All Rights Reserved.
// Khrono Group Safety Critical API Development SCAP
// document
// 
// Text format: asciidoc 8.6.9
// Editor:      Asciidoc Book Editor
//
// Description: Requirements 3.2.1 Github #1 Bugzilla #15991

:Author: Illya Rudkin (spec editor)
:Author Initials: IOR
:Revision: 0.03

// Hyperlink anchor, the ID matches those in 
// 3_1_RequirementList.adoc 
[[gh1]]

ifdef::basebackend-docbook[]
=== Deterministic behavior
endif::[]
ifdef::basebackend-html[]
=== {chapter-id}.{chapter-sub-id}.{counter:section-id}. Deterministic behavior
endif::[]

For the API to be deterministic, no randomness or unpredictability in the development of future states of the system may exist. A deterministic API will always produce the exact same output, both as far as user experience and in the contract with the application, from a given starting condition or initial state.

This requirement applies to functional and behavioral output only. It does not apply to platform timing or system resources. From an API perspective, the API needs to list and describe all state transitions that occur due to the application calling the API function.

Deterministic systems are those whose behavior is predictable, balanced and repeatable under all conditions, work loads and failure states.

When describing an API function, all of its parameters and state transitions shall be documented.
For each state transition there shall be a description of the before and after state. 

If a there is a state transition discovered which is not documented then it is the responsibility of the implementers to report the anomaly to the Khronos Working Group responsible for the SC API specification.

[width="70%", cols="3,^,^", options="header"]
|====================
|**Safety critical standard** | **Relevant** | **Notes**
| DO-178C/ED-12C | ✓ |  
| ISO 26262      | ✓ |  
| IEC 62304      | ✓ |   
|====================
