// (C) Copyright 2014-2017 The Khronos Group Inc. All Rights Reserved.
// Khrono Group Safety Critical API Development SCAP
// document
// 
// Text format: asciidoc 8.6.9
// Editor:      Asciidoc Book Editor
//
// Description: Requirements 2.3 Terminology

:Author: Illya Rudkin (spec editor)
:Author Initials: IOR
:Revision: 0.02

=== {chapter-id}.{counter:chapter-sub-id}. Terminology

The key words *must*, *required*, *shall*, *should*, *recommend*, *may*, and *optional* in this document are to be interpreted as described in RFC 2119: 
http://www.ietf.org/rfc/rfc2119.txt.

===== must 
When used alone, this word, or the term required, means that the definition is an absolute requirement of the specification. When followed by not (“must not” ), the phrase means that the definition is an absolute prohibition of the specification. 

===== should 
When used alone, this word, or the adjective recommended, means that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course. When followed by not (“should not”), the phrase means that there may exist valid reasons in particular circumstances when the particular behavior is acceptable or even useful, but the full implications should be understood and the case carefully weighed before implementing any behavior described with this label. 

===== may
This word, or the adjective optional, means that an item is truly optional. One vendor may choose to include the item because a particular marketplace requires it or because the vendor 4 
feels that it enhances the product while another vendor may omit the same item. An implementation which does not include a particular option must be prepared to interoperate with another implementation which does include the option, though perhaps with reduced functionality. In the same vein an implementation which does include a particular option must be prepared to interoperate with another implementation which does not include the option (except, of course, for the feature the option provides). 

===== can and cannot
The additional terms *can* and *cannot* are to be interpreted as follows: 

*can*

This word means that the particular behavior described is a valid choice for an application, and is never used to refer to implementation behavior. 

*cannot* 

This word means that the particular behavior described is not achievable by an application. For example, an entry point does not exist, or shader code is not capable of expressing an operation. 

NOTE: There is an important distinction between *cannot* and *must not*, as used in this document. *Cannot* means something the application literally is unable to express or accomplish through the API, while *must not* means something that the application is capable of expressing through the API, but that the consequences of doing so are undefined and potentially unrecoverable for the implementation. 


