// (C) Copyright 2014-2017 The Khronos Group Inc. All Rights Reserved.
// Khronos Group Safety Critical API Development SCAP
// document
// 
// Text format: asciidoc 8.6.9
// Editor:      Asciidoc Book Editor
//
// Description: Requirements 3.2.5 Github #5

:Author: Daniel Herring
:Author Initials: DMH
:Revision: 0.02

// Hyperlink anchor, the ID matches those in 
// 3_1_RequirementList.adoc 
[[gh5]]

=== {chapter-id}.{chapter-sub-id}.{counter:section-id}. Notification of change of state

A hindrance to safety certification is the use of event driven execution of the application. 
The use of event driven execution can cause the worst case execution time of a system to be 
indeterminate or very large. To reduce the worst case execution time of all functionality within 
the system the use of asynchronous events causing code to execute is discouraged in a safety 
critical API. As such the application should have no need to define functionality which is executed
by the API code base. Where such asynchronous events are used to define a change to the system's
state, the API shall provide the ability to the application to query the state of asynchronous
events which change the system's state. 

Worst case execution time should be able to be determined by the end system integrator and software
team through analysis and testing. The API should not rely on or specify the use of asynchronous 
immediate event handling such as Interrupt Service Routines (ISRs). 

[width="70%", cols="3,^,^", options="header"]
|====================
|**Safety critical standard** | **Relevant** | **Notes**
| DO-178C/ED-12C |  - |  
| ISO 26262      |  - |  
| IEC 62304      |  - |   
|====================
